### ISSUE TITLE
support for qos in iosxe_class_map

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#100]
Hi,

Is it possible to add support to the iosxe_class_map resource

I currently need to use CLI:

resource "iosxe_cli" "classmap-routing" {
  cli    = <<-EOT
  class-map match-any CM-ROUTING
   match ip dscp ef
   match ip dscp af41
   match ip dscp cs6
  EOT
}

kind regards

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/e93e3acf2e73562c73e8462999e135f23a6912c4

**Comment by danischm** [comment]
Added in v0.5.5 release.
