### ISSUE TITLE
support for speed nonegotiate in iosxe_interface_ethernet

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#101]
Hi,

Is it possible to add support for speed nonegotiate in resource iosxe_interface_ethernet?

CLI:

interface TwentyFiveGigE1/0/1
 speed nonegotiate

On a C9500-48Y4C (fiber ony) you cannot specify the speed.
Only nonegotiate.

regards

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/03b53fae30d1677a89a5ab40885d9470edd52076

**Comment by thomasnoppe** [comment]
Thank you!

**Comment by danischm** [comment]
Added in v0.5.5 release.
