### ISSUE TITLE
resource to configure flow monitor and flow exporter and flow record

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#105]
Hi,

Would it be possible to create a resource to configure:

- flow record
- flow monitor
- flow exporter

CLI:

flow record FNF-input
 description IPv4 NetFlow
 match ipv4 source address
 match ipv4 destination address
 match transport source-port
 match transport destination-port
 match ipv4 protocol
 match interface input
 match ipv4 tos
 match flow direction
 collect interface output
 collect counter bytes long
 collect counter packets long
 collect transport tcp flags
 collect timestamp absolute first
 collect timestamp absolute last
!
flow record FNF-output
 description IPv4 NetFlow
 match ipv4 source address
 match ipv4 destination address
 match transport source-port
 match transport destination-port
 match ipv4 protocol
 match interface output
 match ipv4 tos
 match flow direction
 collect interface input
 collect counter bytes long
 collect counter packets long
 collect transport tcp flags
 collect timestamp absolute first
 collect timestamp absolute last
!
flow exporter Scrutinizer
 description Export to Scrutinizer
 destination x.x.x.x
 source Loopback0
 transport udp 2055
 template data timeout 60

!
flow monitor Scrut_mon_input
 description IPv4 FNF ingress exports
 exporter Scrutinizer
 cache timeout active 60
 record FNF-input
!
flow monitor Scrut_mon_output
 description IPv4 FNF egress exports
 exporter Scrutinizer
 cache timeout active 60
 record FNF-output
!

kind regards

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/2cd04bd48a880747e25da56e027f9128c16e5de7, https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/8b09f848ff2978d121f84f1b1db852f40c17201a, https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/65134bd12644cce08d4d27f054de23951d38fe0c

**Comment by danischm** [comment]
Added in v0.5.6 release.
