### ISSUE TITLE
support for advertisement-interval in iosxe_bgp_ipv4_unicast_vrf_neighbor

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#106]
Hi,

Is it possible to add support for configuring the advertisement-interval in resource iosxe_bgp_ipv4_unicast_vrf_neighbor?

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/d4665e99bb3663aa23a05549ca26cee43815b06b

**Comment by danischm** [comment]
Added in v0.5.6 release.
