### ISSUE TITLE
ip prefix-list description

### ISSUE THREAD

**Issue by grotewortel** [CiscoDevNet/terraform-provider-iosxe#108]
Description  
The option to configure the description of a prefix list (`ip prefix-list NAME description`) seems to be missing.

Please note that the description and the actual prefix list data are on different data levels.

**show running-config | section ip prefix-list**  
This is part of the running config:

```
ip prefix-list TEST description TEST_TEST_TEST
ip prefix-list TEST seq 10 permit 1.2.3.4/30 le 32
```

**json path: .data["Cisco-IOS-XE-native:native"].ip["prefix-lists"]**  
This is the restconf-json formatted running config:

```
{
  "prefixes": [
    {
      "name": "TEST",
      "no": 10,
      "action": "permit",
      "ip": "1.2.3.4/30",
      "le": 32
    }
  ],
  "prefix-list-description": [
    {
      "name": "TEST",
      "description": "TEST_TEST_TEST"
    }
  ]
}
```

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/5768470c61ee5a8c41626ace45c06683ac0ce3bf

**Comment by danischm** [comment]
Added in v0.5.6 release.
