### ISSUE TITLE
Add BFD support for interface and BGP

### ISSUE THREAD

**Issue by tiagolugarini** [CiscoDevNet/terraform-provider-iosxe#12]
Please add BFD support for interfaces and BGP.

**Comment by danischm** [comment]
Could you please add the related CLI config snippets? Thanks.

**Comment by tiagolugarini** [comment]
When configuring BFD multi-hop, some steps are required.
1: create the BFD template:
`bfd-template multi-hop bfd_template
 interval min-tx 1000 min-rx <number in ms> multiplier <number>`
 
 2: Configure BFD multi-hop map for each BFD test. The example below uses VRF but it can be ignored
 `bfd map ipv4 vrf <DEST VRF> <DEST IP> vrf <SOURCE VRF> <SOURCE IP> <BFD TEMPLATE NAME - Step 1>`
 
 3: Enable BFD for the neighbour inside BGD
 `router bgp 65321
 address-family ipv4 vrf <SOURCE VRF>
  neighbor <DEST IP> fall-over bfd multi-hop
 exit-address-family`
 
 
 Some URLS
 https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_pi/command/iri-cr-book/iri-cr-a1.html#wp1632150118
 https://content.cisco.com/chapter.sjs?uri=/searchable/chapter/content/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-17/irg-xe-17-book/bfd-bgp-multihop-client-support-and-cbit-ipv-and-ipv.html.xml

**Comment by danischm** [comment]
Added in v0.4.0.
