### ISSUE TITLE
Problem applying iosxe_cli on csr 1000v running 17.03.08a

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#132]
resource "iosxe_cli" "test" {
  cli = <<-EOT
  int lo10
  description test
  EOT
  device     = var.csr_router
}

Terraform will perform the following actions:

  module.vpntunnel["csr-nxh-mer4-01"].iosxe_cli.test will be created
  + resource "iosxe_cli" "test" {
      + cli    = <<-EOT
            int lo10
            description test
        EOT
      + device = "csr-nxh-mer4-01"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

module.vpntunnel["csr-nxh-mer4-01"].iosxe_cli.test: Creating...
╷
│ Error: Client Error
│ 
│   with module.vpntunnel["csr-nxh-mer4-01"].iosxe_cli.test,
│   on vpntunnel/main.tf line 129, in resource "iosxe_cli" "test":
│  129: resource "iosxe_cli" "test" {
│ 
│ Failed to send CLI commands, got error: HTTP Request failed: StatusCode 400, RESTCONF errors {Error:[{ErrorType:application ErrorTag:malformed-message ErrorAppTag: ErrorPath: ErrorMessage:invalid path
│ ErrorInfo:}]} {PatchId: GlobalStatus:{Ok:false Errors:{Error:[]}} EditStatus:{Edit:[]} Errors:{Error:[]}}
╵
make: *** [../scripts/Makefile:114: apply] Error 1

**Comment by thomasnoppe** [comment]
I have upgraded my csr1000v to catalyst8000V running 17.09.04.a and there it works.

**Comment by amttel** [comment]
Still an issue with csr1000 Version 17.3.8a,
