### ISSUE TITLE
Issues with `iosxe_interface_tunnel` resource 

### ISSUE THREAD

**Issue by mobig** [CiscoDevNet/terraform-provider-iosxe#31]
When using the new tunnel resource, i get the following error
```
╷
│ Error: Client Error
│
│   with iosxe_interface_tunnel.Tunnel_Interface["router_2-11"],
│   on main.tf line 287, in resource "iosxe_interface_tunnel" "Tunnel_Interface":
│  287: resource "iosxe_interface_tunnel" "Tunnel_Interface" {
│
│ Failed to configure object (PATCH), got error: HTTP Request failed: StatusCode 400, RESTCONF errors {Error:[{ErrorType:application ErrorTag:malformed-message ErrorAppTag: ErrorPath:/Cisco-IOS-XE-native:native/interface/Tunnel
│ ErrorMessage:unknown element: tunnel in /ios:native/ios:interface/ios:Tunnel[ios:name='11']/ios:tunnel ErrorInfo:}]} {PatchId: GlobalStatus:{Ok:false Errors:{Error:[]}} EditStatus:{Edit:[]} Errors:{Error:[]}}
╵
```
In testing, i found this error to be specific to the `tunnel_destination_ipv4` attribute of the resource 

Here is the call Terraform is making to the box:
```
 https://192.168.0.157/restconf/data/Cisco-IOS-XE-native:native/interface/Tunnel, {{"Cisco-IOS-XE-native:Tunnel":
{"name":"12","description":"test tunnel","ip":{"proxy-arp":false,"redirects":false,"Cisco-IOS-XE-icmp:unreachables":false,"address":{"primary":{"address":"12.1.1.2","mask":"255.255.255.0"}}},"Cisco-IOS-XE-tunnel:tunnel":{"source":"2.1.1.1"},"tunnel":{"destination-config":{"ipv4":"7.1.1.1"}}}}}
```
I tested this in postman and did confirm that there is something weird about the call the resource is making as i got the same error in postman. Running the resource without the tunnel destination corrects the issue and i'm able to create the interface. Obviously we need to set a destination on the tunnel

**Comment by danischm** [comment]
Thanks for raising the issue! Should be fixed in the next release: https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/f9bdb17196abe3585f3612106239c19a506a12f3

**Comment by mobig** [comment]
is there any update on the next release? we need to deploy this in production

**Comment by danischm** [comment]
we should have a new release in the coming days

**Comment by danischm** [comment]
Added in v0.4.0.
