### ISSUE TITLE
Add support for static VRF route

### ISSUE THREAD

**Issue by mobig** [CiscoDevNet/terraform-provider-iosxe#32]
We need the ability to add static routes to a VRF. It would be helpful if this was added to the native provider.

Thanks again for all the work on this

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/e83b1b4862712d8d751e1b89c254d9eb10e20381

**Comment by mobig** [comment]
any idea when this will be published into a release?

**Comment by danischm** [comment]
Added in v0.4.0.
