### ISSUE TITLE
Port-channel

### ISSUE THREAD

**Issue by patricer98** [CiscoDevNet/terraform-provider-iosxe#36]
Hi,
Thank you for this new provider.
I m looking for the googd method to obtain a int Po in trunk mode(ok), with two physical interfaces(ok),  to transport , One or more vlans(not ok)

Regards

**Comment by danischm** [comment]
Could you share an example Terraform config of what is working and what is not working?

**Comment by patricer98** [comment]
Hi Daniel

Thanks for your reply and interest.
Please find bellow some  material :

resource "iosxe_interface_port_channel" "po100" {
  name                           = 100
  description                    = "Portchannel100"
  shutdown                       = false
}

resource "iosxe_interface_ethernet" "twe1-0-3" {
  type                           = "TwentyFiveGigE"
  name                           = "1/0/3"
  description                    = "testconf"
  shutdown                       = false
  channel_group_mode             = "auto"
  channel_group_number           = 100
}

resource "iosxe_interface_ethernet" "twe2-0-3" {
  type                           = "TwentyFiveGigE"
  name                           = "2/0/3"
  description                    = "testconf"
  shutdown                       = false
  channel_group_mode             = "auto"
  channel_group_number           = 100
}

I dont understand / dont see any option how to put some vlan on po100

resource "iosxe_interface_port_channel" "po100" {
  name                           = 100
  description                    = "Portchannel100"
  shutdown                       = false
   # vrf_forwarding                 = "VRF1"
  # ipv4_address                   = "192.0.2.1"
  # ipv4_address_mask              = "255.255.255.0"
  # ip_access_group_in             = "1"
  # ip_access_group_in_enable      = true
  # ip_access_group_out            = "1"
  # ip_access_group_out_enable     = true
  # ip_dhcp_relay_source_interface = "Loopback100"
  # helper_addresses = [
  #   {
  #     address = "10.10.10.10"
  #     global  = false
  #   }
  # ]
}

in cli mode the po manage the interfaces so i think it ss the same with terraform

perhaps with the template..
Regards.
Patrice.

**Comment by danischm** [comment]
You need this (https://registry.terraform.io/providers/CiscoDevNet/iosxe/latest/docs/resources/interface_switchport) resource to apply l2 config to an interface.

**Comment by patricer98** [comment]
thanks you 

[type](https://registry.terraform.io/providers/CiscoDevNet/iosxe/latest/docs/resources/interface_switchport#type) (String) Interface type

    Choices: GigabitEthernet, TwoGigabitEthernet, FiveGigabitEthernet, TenGigabitEthernet, TwentyFiveGigE, FortyGigabitEthernet, HundredGigE, TwoHundredGigE, FourHundredGigE

in fact there is no PO type in the terraform switchport, so i ll test with this mode directly on the interface.
regards.

**Comment by patricer98** [comment]
:-)
have a nice weekend

**Comment by Jayboyok** [comment]
Please help me understand why would you guys close all my ports? Tell me what I've done wrong. I'm not able to receive messages

**Comment by Jayboyok** [comment]
![Screenshot_20230820-144645.png](https://github.com/CiscoDevNet/terraform-provider-iosxe/assets/142549733/b9677e05-8875-4f95-ad47-ff6249bbe175)

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/e4b9e765770c9edb67aa23d4864f1df4fe1dc345

**Comment by danischm** [comment]
Added in v0.4.0.

**Comment by patricer98** [comment]
hi Daniel
Thank you for the port-channel add on.
it works well
regards

**Comment by danischm** [comment]
Great, thx!
