### ISSUE TITLE
What does this mean

### ISSUE THREAD

**Issue by ghost** [CiscoDevNet/terraform-provider-iosxe#41]
Why is my location showing null? The public ip6 address is showing as unregistered domain. Would this be why no calls or texts messages are coming to my device. How do I fix? I'm not interested in any domain. Just wanted my device to work

**Comment by Jayboyok** [comment]
![Screenshot_20230827-164030](https://github.com/CiscoDevNet/terraform-provider-iosxe/assets/142549733/29a54387-4755-412c-b4ea-5a6263f0c2ed)

**Comment by Jayboyok** [comment]
![Screenshot_20230827-164022](https://github.com/CiscoDevNet/terraform-provider-iosxe/assets/142549733/c523d388-8a38-4f8d-8f04-a723c3e3a96d)

**Comment by Jayboyok** [comment]
![Screenshot_20230827-164149](https://github.com/CiscoDevNet/terraform-provider-iosxe/assets/142549733/073d1265-73ee-424b-bdce-788df9167e22)
