### ISSUE TITLE
Declarative

### ISSUE THREAD

**Issue by lemontree61089** [CiscoDevNet/terraform-provider-iosxe#6]
Hello,

Testing this provider, it looks like everything is imperative at this time. Is there any plans to release declarative features(as opposed to imperative)?
This would be really helpful (in my opinion) in environments like EVPN/VXLAN fabric where adding/editing/deleting L2VNI/L3VNI services happens often.

Nevertheless, happy to see Terraform coming to Cisco devices!

**Comment by poroping** [comment]
@lemontree61089  Happy to take a look at implementing evpn and vxlan into my provider, open an issue on my repo with the yang payloads and endpoints. Even easier if Cisco would release some generated Go models from the Yang models... Hint hint ;)

**Comment by robertcsapo** [comment]
@lemontree61089, @poroping  What kind of EVPN configuration would be the most crucial?
With 17.7+ you can translate CLI config to RESTCONF ```show running-config | format restconf-json```

**Comment by lemontree61089** [comment]
@robertcsapo To me, it is all operations related to EVPN services. Such as creating a VRF with the associated L3VNI/VXLAN config, the deployment of a VLAN with the associated L2VNI/VXLAN config and so on

**Comment by robertcsapo** [comment]
@lemontree61089 here is two alternatives

- https://registry.terraform.io/providers/robertcsapo/ciscoevpn/latest
- https://registry.terraform.io/modules/netascode/evpn-overlay/iosxe/latest

**Comment by tschuxxi** [comment]
The slides on this repo say "Pahse II: new declarative features", I hope someone is working on this

**Comment by elongstreet88** [comment]
This was driving me crazy, so I made a generic restconf one:
https://github.com/kwikcode/terraform-provider-restconf

**Comment by danischm** [comment]
Revamped 0.3.0 release is fully declarative.
