### ISSUE TITLE
Resource iosxe_line missing authorization/transport input

### ISSUE THREAD

**Issue by sthoneder** [CiscoDevNet/terraform-provider-iosxe#60]
Resource iosxe_line is missing two common needed parts which are /native/line/vty/authorization/exec and /native/line/vty/transport/input

CLI Configuration
line vty 0 4
 authorization exec 'authorization list name'
 transport input ssh

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/986dd39a68be902b11d3b0c205d09b087cff6953

**Comment by danischm** [comment]
Added in 0.5.2 release.
