### ISSUE TITLE
Interface commands for authentication and dot1x

### ISSUE THREAD

**Issue by defiant214** [CiscoDevNet/terraform-provider-iosxe#63]
Perusing through the docs, I don't see a way to enable port-based authentication commands. The global commands are there, but I am looking for a way to do the following on a port:
```
authentication host-mode multi-auth
authentication order dot1x mab
authentication priority dot1x mab
authentication port-control auto
authentication periodic
authentication timer reauthenticate server
mab
dot1x pae authenticator
dot1x timeout tx-period 5
dot1x max-req 3
dot1x max-reauth-req 3
```

Can you enable this functionality or point me to where it might be in the docs? Thanks!

**Comment by danischm** [comment]
Thanks for raising an issue. Some of those commands are supported with the `iosxe_template` resource, which could then be applied to an interface. We will look at adding support for those at the interface level as well.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/af414cfdf465aceed2bb60aea187a5014eff8dd0

**Comment by danischm** [comment]
Added in 0.5.2 release.
