### ISSUE TITLE
Multiple hosts

### ISSUE THREAD

**Issue by jltomasg** [CiscoDevNet/terraform-provider-iosxe#7]
Wondering if there is an easy technique in order to apply the same configuration to multiple hosts.
One approach is to use multiple alias but it is a bit too convoluted.

Thank you so much.

**Comment by danischm** [comment]
Addressed in revamped 0.3.0 release. https://registry.terraform.io/providers/CiscoDevNet/iosxe/latest/docs/guides/manage_multiple_devices
