### ISSUE TITLE
ip community-list

### ISSUE THREAD

**Issue by grotewortel** [CiscoDevNet/terraform-provider-iosxe#78]
Description  

The option to create an `ip community-list` seems to be missing.  

Can you please tell us how to configure or implement this feature?

**show running-config | section include community-list**  
This is part of an example running config:

```
ip community-list standard TEST permit 65000:500
```

**json path: .data["Cisco-IOS-XE-native:native"].ip**  
This is the restconf-json formatted running config:

```
{
  "Cisco-IOS-XE-bgp:ip-community-list": {
    "community-list": {
      "standard": [
        {
          "name": "TEST",
          "action": [
            {
              "action": "permit",
              "bgp-community": [
                {
                  "bgp-community": "65000:500"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/cd5ada84ed3780d2ce89faa605889c8d39ff72c4

**Comment by grotewortel** [comment]
Thank you for all the 6 updates!

We will test all of them.
Do you have a planning for the next release?

**Comment by danischm** [comment]
Probably later today.

**Comment by danischm** [comment]
Added in 0.5.2 release.
