### ISSUE TITLE
ip bgp-community new-format

### ISSUE THREAD

**Issue by grotewortel** [CiscoDevNet/terraform-provider-iosxe#79]
Description  

The option to configure `ip bgp-community new-format` seems to be missing.  

Can you please tell us how to configure or implement this feature?

**show running-config | section ip bgp-community**  
This is part of an example running config:

```
ip bgp-community new-format
```

**json path: .data["Cisco-IOS-XE-native:native"].ip**  
This is the restconf-json formatted running config:

```
{
  "bgp-community": {
    "new-format": [
      null
    ]
  }
}
```

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/e888ccb661ca0f04b1a280aeaacba6651c905232

**Comment by danischm** [comment]
Added in 0.5.2 release.
