### ISSUE TITLE
 Static Routes with Interfaces Specified Don't Apply

### ISSUE THREAD

**Issue by fsecuritynz** [CiscoDevNet/terraform-provider-iosxe#85]
There is no support to create static-routes with a interface specified. This is quite important for "Null" routes.

`resource "iosxe_static_route_vrf" "static_default_vrf_internet_routeB" {
  vrf = "internet"
  routes = [
    {
      prefix = "1.1.1.1"
      mask   = "255.255.255.255"
      next_hops = [
        {
          next_hop = "null"
          name     = "test null route"
        }
      ]
    }
  ]
}`

**TERRAFORM APPLY FAILURE**

`➜  pe1 git:(main) ✗ terraform apply
iosxe_prefix_list.isp_internet_pl-in: Refreshing state... [id=Cisco-IOS-XE-native:native/ip/prefix-lists]
iosxe_prefix_list.isp_internet_pl-out: Refreshing state... [id=Cisco-IOS-XE-native:native/ip/prefix-lists]
iosxe_static_route_vrf.static_default_vrf_internet_route: Refreshing state... [id=Cisco-IOS-XE-native:native/ip/route/vrf=internet]
iosxe_prefix_list.isp_internet_pl-all: Refreshing state... [id=Cisco-IOS-XE-native:native/ip/prefix-lists]
iosxe_bgp_ipv4_unicast_vrf_neighbor.ce1_to_pe1: Refreshing state... [id=Cisco-IOS-XE-native:native/router/Cisco-IOS-XE-bgp:bgp=4771/address-family/with-vrf/ipv4=unicast/vrf=internet/ipv4-unicast/neighbor=200.1.1.2]
iosxe_interface_ethernet.ge3: Refreshing state... [id=Cisco-IOS-XE-native:native/interface/GigabitEthernet=3]
iosxe_interface_ethernet.ge2: Refreshing state... [id=Cisco-IOS-XE-native:native/interface/GigabitEthernet=2]
iosxe_bgp_address_family_ipv4_vrf.isprouterbgpvrfinternet: Refreshing state... [id=Cisco-IOS-XE-native:native/router/Cisco-IOS-XE-bgp:bgp=4771/address-family/with-vrf/ipv4=unicast]
iosxe_route_map.isp_internet_rm-static: Refreshing state... [id=Cisco-IOS-XE-native:native/route-map=rm-static]
iosxe_route_map.isp_internet_rm-in: Refreshing state... [id=Cisco-IOS-XE-native:native/route-map=rm-pe1-in]
iosxe_bgp.isprouterbgp: Refreshing state... [id=Cisco-IOS-XE-native:native/router/Cisco-IOS-XE-bgp:bgp=4771]
iosxe_vrf.internetvrf: Refreshing state... [id=Cisco-IOS-XE-native:native/vrf/definition=internet]
iosxe_route_map.isp_internet_rm-out: Refreshing state... [id=Cisco-IOS-XE-native:native/route-map=rm-pe1-out]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # iosxe_static_route_vrf.static_default_vrf_internet_routeB will be created
  + resource "iosxe_static_route_vrf" "static_default_vrf_internet_routeB" {
      + id     = (known after apply)
      + routes = [
          + {
              + mask      = "255.255.255.255"
              + next_hops = [
                  + {
                      + name     = "test null route"
                      + next_hop = "null"
                    },
                ]
              + prefix    = "1.1.1.1"
            },
        ]
      + vrf    = "internet"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

iosxe_static_route_vrf.static_default_vrf_internet_routeB: Creating...
iosxe_static_route_vrf.static_default_vrf_internet_routeB: Still creating... [10s elapsed]
iosxe_static_route_vrf.static_default_vrf_internet_routeB: Still creating... [20s elapsed]
╷
│ Error: Client Error
│ 
│   with iosxe_static_route_vrf.static_default_vrf_internet_routeB,
│   on resource-static_route.tf line 16, in resource "iosxe_static_route_vrf" "static_default_vrf_internet_routeB":
│   16: resource "iosxe_static_route_vrf" "static_default_vrf_internet_routeB" {
│ 
│ Failed to configure object (PATCH), got error: HTTP Request failed: StatusCode 400, RESTCONF errors {Error:[{ErrorType:application ErrorTag:invalid-value ErrorAppTag: ErrorPath:/Cisco-IOS-XE-native:native/ip/route/vrf ErrorMessage:inconsistent value: Device refused one or more commands ErrorInfo:}]} {PatchId:
│ GlobalStatus:{Ok:false Errors:{Error:[]}} EditStatus:{Edit:[]} Errors:{Error:[]}}
╵
➜  pe1 git:(main) ✗ `

**Comment by danischm** [comment]
The correct syntax would be:

```
resource "iosxe_static_route_vrf" "static_default_vrf_internet_routeB" {
  vrf = "internet"
  routes = [{
    prefix = "1.1.1.1"
    mask   = "255.255.255.255"
    next_hops = [{
      next_hop = "Null0"
      name     = "test null route"
    }]
  }]
}
```

**Comment by fsecuritynz** [comment]
Excellent, that's confirmed it as working. Thanks!
