### ISSUE TITLE
Add support for BGP Soft Reconfiguration

### ISSUE THREAD

**Issue by fsecuritynz** [CiscoDevNet/terraform-provider-iosxe#87]
There is no support for BGP soft reconfiguration currently, a very important feature.

https://registry.terraform.io/providers/CiscoDevNet/iosxe/latest/docs/resources/bgp_ipv4_unicast_vrf_neighbor

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/97421d24dfff0ec7321fd9141868d3b50b5d8a2a

**Comment by danischm** [comment]
Added in 0.5.2 release.
