### ISSUE TITLE
Resource iosxe_ntp is not replacing ntp servers

### ISSUE THREAD

**Issue by gsantos1979** [CiscoDevNet/terraform-provider-iosxe#9]
After make some changes on resource "iosxe_ntp" we notice that the old NTP Servers are never removed...

Before the change, we have the following configurations on router:
sw1#show runn | inc ntp
ntp source GigabitEthernet0/0
ntp server vrf Mgmt-vrf 1.1.1.1 prefer version 2
ntp server vrf Mgmt-vrf 2.2.2.2 version 2

Here the changes on terraform:
Terraform will perform the following actions:

  # iosxe_ntp.ntp_servers["sw1"] will be updated in-place
  ~ resource "iosxe_ntp" "ntp_servers" {
        id                           = "Cisco-IOS-XE-native:native/ntp"
      ~ server_vrfs                  = [
          ~ {
                name    = "Mgmt-vrf"
              ~ servers = [
                  ~ {
                      ~ ip_address = "1.1.1.1" -> "ntp1.domain"
                    },
                  ~ {
                      ~ ip_address = "2.2.2.2" -> "ntp2.domain"
                    },
                ]
            },
        ]
    }

iosxe_ntp.ntp_servers["sw1"]: Modifying... [id=Cisco-IOS-XE-native:native/ntp]
iosxe_ntp.ntp_servers["sw1"]: Modifications complete after 2s [id=Cisco-IOS-XE-native:native/ntp]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

After the change, we have the following configurations on router:
sw1#show runn | inc ntp
ntp source GigabitEthernet0/0
ntp server vrf Mgmt-vrf 1.1.1.1 prefer version 2
ntp server vrf Mgmt-vrf 2.2.2.2 version 2
ntp server vrf Mgmt-vrf ntp1.domain prefer version 2
ntp server vrf Mgmt-vrf ntp2.domain version 2

$ terraform version
Terraform v1.5.3

Resource code:
```
resource "iosxe_ntp" "ntp_servers" {
    for_each                            = toset([for router in local.routers : router.name])
    device                              = each.key
    authenticate                    = false
    logging                             = false
    trap_source_gigabit_ethernet = "0/0"
    server_vrfs = [
    {
      name                              = "Mgmt-vrf"
      servers = [ for ntp in local.global.NTPServers :
        {
          ip_address                = ntp.Server
          prefer                        = ntp.Prefer
          version                       = 2
        }
      ]
    }
    ]
}
```

**Comment by danischm** [comment]
Thanks for raising this issue! Fixed in 0.3.1 release.
