### ISSUE TITLE
support for bgp router-id in iosxe_bgp_address_family_ipv4_vrf

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#92]
Would it be possible to add support for bgp router-id configuration in iosxe_bgp_address_family_ipv4_vrf?
Similar to the router_id_loopback in iosxe_bgp.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/d0bbb75d80718c3e8c09264a8cd7fee5906477e6

**Comment by danischm** [comment]
Added in 0.5.3 release.
