### ISSUE TITLE
support for ha-mode graceful-restart in bgp_ipv4_unicast_vrf_neighbor

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#93]
Hi

Would it be possible to add support for ha-mode graceful-restart in bgp_ipv4_unicast_vrf_neighbor please?

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/95b241a043bff8b974dc10ffd168767c84ad06fd

**Comment by thomasnoppe** [comment]
thank you!

**Comment by danischm** [comment]
Added in 0.5.3 release.
