### ISSUE TITLE
support for next-hop-self in iosxe_bgp_ipv4_unicast_vrf_neighbor

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#95]
Hi,
           
Is it possible to add support for next-hop-self in resource iosxe_bgp_ipv4_unicast_vrf_neighbor?

CLI:

 neighbor 10.227.251.20 next-hop-self

Thank you!

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/3898c78bde9a09d93f7b422e75acd9467541ab5f

**Comment by danischm** [comment]
Added in 0.5.4 release.
