### ISSUE TITLE
support for set as-path replace in resource iosxe_route_map

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#96]
Hi,

Is it possible to add support for:

 set as-path replace in resource iosxe_route_map

CLI:

set as-path replace any

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/f290910ec19188f962da821a2b64640c6ecf13cf

**Comment by danischm** [comment]
Added in 0.5.4 release.
