### ISSUE TITLE
support for bandwith command in iosxe_interface_ethernet

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#97]
Hi,

Would it be possible to add support for the bandwith command in iosxe_interface_ethernet?

CLI example:

interface TwentyFiveGigE1/0/1
 bandwidth 300000

kind regards

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/41ed80e9716ac2625d16b902234c6f6aa11bda5f

**Comment by danischm** [comment]
Added in v0.5.5 release.
