### ISSUE TITLE
support for service-policy in iosxe_interface_ethernet

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#98]
Hi,

Is it possible to add support for applying a service-policy on iosxe_interface_ethernet?

CLI example:

interface TwentyFiveGigE1/0/1
 service-policy output PM-UZL-SHAPE-NXH
end

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/497ce9f44f8e6f0d34a0773f95e89598346a0d46

**Comment by danischm** [comment]
Added in v0.5.5 release.
