### ISSUE TITLE
iosxe_policy_map resource support for qos

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-iosxe#99]
Hi,

Is it possible to add support to the iosxe_policy_map resource

I currently need to use CLI:

resource "iosxe_cli" "policymap_uzl-shape-nxh" {
  cli        = <<-EOT
  policy-map PM-UZL-SHAPE-NXH
    class CM-UZL-JWS
      shape average percent 70
    class CM-UZL-ROUTING
      priority level 1
    class class-default
  EOT
}

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxe/commit/39c4daf76e504c1b6e2e957e2ad077ad4a963ef1

**Comment by danischm** [comment]
Added in v0.5.5 release.
